### ISSUE TITLE
Issue searching COHA

### ISSUE THREAD

**Issue by scaevola01** [ekbrown/byucorpora#2]
So, I try the following code, and get the following message:

> >  search_coha("erstwhile")
> 	Working on search term 1 of 1: erstwhile
> 		Match 1 of 1 for search term erstwhile: erstwhile
> Error in overscope_eval_next(overscope, expr) : object 'X5' not found

Can you diagnose this? I'm helping design a new course on using R in historical linguistics, and being able to search COHA would be a huge asset to our lesson plan.

**Comment by ekbrown** [comment]
When the interface changed last year, I didn't update the package. If you
know how to use the httr and rvest packages, it's not too complicated. If
you wanna send a pull request, that'd be great.

2017-10-19 10:51 GMT-06:00 scaevola01 <notifications@github.com>:

**Comment by scaevola01** [comment]
Dear Earl,

Thanks, I’ll look into that. However, because of other commitments, it likely won’t happen until early 2018, if I’m able to do it at all.

John

**Comment by scaevola01** [comment]
[cohaoutput.xlsx](https://github.com/ekbrown/byucorpora/files/1480121/cohaoutput.xlsx)
Earl, I ended up taking a crack at this earlier. I partially solved the problem by changing row 18 in helper_fun.R from:
> res_table <- rvest::html_table(rvest::html_nodes(kwic_xml, "table")[[2]], fill = T)
to
> res_table <- rvest::html_table(rvest::html_nodes(kwic_xml, "table")[[3]], fill = T)

That gives me back the data. However, the data that I get back is pretty different from the data on the screen. Instead of getting 10 columns of data, I only get 3: the case, the year and section (rolled into one), and the entire text of the sample (not divided into pre_context, match, and post_context). That breaks the if statement that starts at line 21 of the same function.

Before I try to fix the if statement, can you tell me if the data that I'm getting back makes sense to you? Should the data still be divided up as it is on the screen? Why am I not getting back any source data? Etc. If this is a known issue with the change that COHA made, that's fine. I just want to confirm that I'm not "quitting" too early.

I've attached a copy of my output for you to evaluate.

**Comment by ekbrown** [comment]
Sounds like you're on the right track. Sorry I haven't looked at that
package yet. I have two new preps this semester that are taking most of my
time. I hope to update it over winter break.

Earl Brown

**Comment by jflanaga** [comment]
HI,

I know you are not maintaining the package any longer, but I thought I would just write a short observation in case scaevola01 is following. 

You can get separate columns for pre_context, match, and post_context for COHA and COCA by adding

`kwic_page <- stringr::str_replace_all(kwic_page, "<b>", "</td><td>")`
`kwic_page <- stringr::str_replace_all(kwic_page, "</b>", "</td><td>")`

in `helper_fun.R`

(I imagine you could actually delete some of the options that are already there but I've only looked at COHA. 

I'm still trying to figure out what causing the issues with the other columns. At first, I thought it was just because the wrong columns were de-selected (that is, it should be 

`res_table <- dplyr::select(res_table, -(X5:X7))` 

However, that didn't work with the package (it does actually make a difference with `create_kwic_table()` when I downloaded the html and tried working just with the function to parse the html).  Something else must be going on (as well).

Anyways, it was a nice package, and gives me some things to think about.

**Comment by jflanaga** [comment]
Sorry, last comment. Actually, the old interface is still being maintained (at least for the time being). Reverting the changes made for the new interface and then changing the URL (e.g, `https://corpus.byu.edu/coha/old/`) resolves the issue. The only issue is adding meaningful names for the columns, as that isn't specified for COHA.
